version: '2'

services:
  web:
    build:
        context: .
        dockerfile: Dockerfile
        args:
            GITHASH: ff864e04f882e8379f19dcf4d18398ca19ec8009
    environment:
        - persistence_persistenceManagerImplementationClass=de.fraunhofer.iosb.ilt.sta.persistence.postgres.stringid.PostgresPersistenceManagerString
        - persistence_idGenerationMode=ServerAndClientGenerated
    ports:
      - 8080:8080
      - 1883:1883
    depends_on:
      - database

  database:
    image: mdillon/postgis:latest
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    ports:
        - 5432:5432
    volumes:
      - postgis_volume:/var/lib/postgresql/data

volumes:
    postgis_volume:
