version: '2'

services:
  gui:
    build:
        context: .
        dockerfile: Dockerfile
        args:
                #GITHASH: 8c038a3cee0da501cc1aeb37f2dd8e11f4ca663f
            GITHASH: 89679e9d72c2f4abc55a0a6aeb45fde5b9f2c8a3
    environment:
        - persistence_persistenceManagerImplementationClass=de.fraunhofer.iosb.ilt.sta.persistence.postgres.stringid.PostgresPersistenceManagerString
        - persistence_idGenerationMode=ServerAndClientGenerated
    restart: unless-stopped
    ports:
      - 8080:8080
      - 1883:1883
    depends_on:
      - database

  database:
    build:
      #image: mdillon/postgis:latest
      context: ../postgis_wale
      dockerfile: Dockerfile
      #image: mdillon/postgis:latest
    restart: unless-stopped
    environment:
      - POSTGRES_DB=sensorthings
      - POSTGRES_USER=sensorthings
      - POSTGRES_PASSWORD=ChangeMe
    ports:
        - 5432:5432
    volumes:
      - postgis_data_volume:/var/lib/postgresql/data
      - postgis_backup_volume:/var/lib/postgresql/backup

volumes:
    postgis_data_volume:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/root/smartaqnet-dev/volumes/frost/postgis_data_volume'
    postgis_backup_volume:
      driver: local
      driver_opts:
        type: 'none'
        o: 'bind'
        device: '/root/smartaqnet-dev/volumes/frost/postgis_backup_volume'
