version: '2'

services:
  gui:
    build:
        context: .
        dockerfile: Dockerfile
        args:
                #GITHASH: 8c038a3cee0da501cc1aeb37f2dd8e11f4ca663f
            GITHASH: d5b7b927919ecbe7423b64956fb040624b34c1b5
    environment:
        - persistence_persistenceManagerImplementationClass=de.fraunhofer.iosb.ilt.sta.persistence.postgres.stringid.PostgresPersistenceManagerString
        - persistence_idGenerationMode=ServerAndClientGenerated
    restart: unless-stopped
    ports:
      - 8080:8080
      - 1883:1883
